spring.application.name=mcpclient

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# 2. Minimal & Ultra-Fast Model Allocation (Perfect for Free Tier)
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

server.port=8000

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-server.json