spring.application.name=mcpclient

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# 2. Minimal & Ultra-Fast Model Allocation (Perfect for Free Tier)
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

server.port=8000

#spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-server.json

#spring.ai.mcp.client.stdio.connections.github.command=C:\\Program Files\\nodejs\\npx.cmd
#spring.ai.mcp.client.stdio.connections.github.args[0]=-y
#spring.ai.mcp.client.stdio.connections.github.args[1]=@modelcontextprotocol/server-github
#spring.ai.mcp.client.stdio.connections.github.env.GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
# Increase the MCP client stdio timeout to 60 seconds (default is 20s)
spring.ai.mcp.client.request-timeout=60s

 #2. Custom Java MCP Server Configuration
spring.ai.mcp.client.stdio.connections.spring-ai-mcp.command=C:\\Program Files\\Java\\jdk-17\\bin\\java.exe
spring.ai.mcp.client.stdio.connections.spring-ai-mcp.args[0]=-jar
spring.ai.mcp.client.stdio.connections.spring-ai-mcp.args[1]=C:\\Users\\91902\\OneDrive\\Desktop\\Spring Boot AI\\mcp\\mcpserver\\target\\mcpserver-0.0.1-SNAPSHOT.jar

# 3. Environment variables required by the server to start
#spring.ai.mcp.client.stdio.connections.spring-ai-mcp.env.MONGODB_URL=mongodb://localhost:27017
#spring.ai.mcp.client.stdio.connections.spring-ai-mcp.env.MONGODB_DB_NAME=docflow_hub
