spring.application.name=mcpclient

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# 2. Minimal & Ultra-Fast Model Allocation (Perfect for Free Tier)
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

server.port=8000

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-server.json

spring.ai.mcp.client.stdio.connections.github.command=C:\\Program Files\\nodejs\\npx.cmd
spring.ai.mcp.client.stdio.connections.github.args[0]=-y
spring.ai.mcp.client.stdio.connections.github.args[1]=@modelcontextprotocol/server-github
spring.ai.mcp.client.stdio.connections.github.env.GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}