spring.application.name=mcpserver

server.port=8000

spring.data.mongodb.uri=${MONGODB_URL}
spring.data.mongodb.database=${MONGODB_DB_NAME}

spring.main.web-application-type=none
spring.main.banner-mode=off

logging.level.root=ERROR

logging.file.name=mcpserver.log