spring.application.name=springbootchatmemory
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

# Your Gemini API Key
#spring.ai.google.genai.api-key=${GOOGLE_GEMINI_API_KEY}

# Optional: Specify the model (default is usually gemini-pro or gemini-flash)
# spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.ollama.base-url=http://localhost:11434

server.port=8000

spring.data.mongodb.uri=${MONGODB_URL}
#spring.data.mongodb.database=${MONGODB_DB_NAME}
#debug=true